# Remote Server configration
server:
  hostname: "raahool-HP-Pavilion-15-Notebook-PC"
  port: 22
  username: "raahool"
  password: "REMOTE_SER_PASSWORD"
  source:  "/var/tmp"
  destination: "/opt/uDeploy"
  processor: "/opt/server_action"

# Jira RESTAPI configuration
jira:
  rooturl: "https://codelocked.atlassian.net/rest/api/3"
  username: "kumeriya_rahul@rediffmail.com"
  authtoken: "JIRA_AUTH_TOKEN"
  headers: {
            "Accept":"application/json",
            "Content-Type": "application/json"
           }
  lead: "5bcc40d4653a520f925a8ff3"
  project: "CODELOCKED"
  label: "Interface-Build-Up"
  region: "Global"
  component: "Interface-Oscillator"
  priority: "Low"
  type: "Task"

# Repository Configuration
repository:
  remoterepo: "git@bitbucket.org:raahoolkumeriya/repo-adhoc-space.git"
  localrepo: "/application/repository/repo-adhoc-space"

artifact:
  artifactstart: "DEPLOYME-10"
  artifactends: ".tar.gz"
  artifact_base: "DEPLOYME-10.0.0"
  regexlist: [
            '^DEPLOYME-10.\d*.\d*.\d*$',
            '^DEPLOYME-\d{1,2}.\d{1,2}.\d{1,3}.\d{1,4}$'
          ]
  templatelist: ['COPY_FILES', 'CREATE_DIR', 'MONGO_QUERY', 'ORACLE_QUERY',
            'QUERY', 'RESTORE_FILES', 'UPDATE_ENV_FILE']
  permissionlist: ['775', '777', '776', '765']
  environment: {"ASIA": 'ASIA', "EMEA": 'EMEA', "DEV": "DATABASE"}

udeployspace:
  rooturl: 'https://udeploy.herokuapp.com/version/'
  headers: {
            "Accept":"application/json",
            "Content-Type": "application/json"
          }
  

# Slack Configuration
slack:
  authtoken: "SLACK_API_TOKEN"
  channelid: "CPDSD2B4N"

# Logging configuration
logging:
  version: 1
  formatters:
    xetra:
      format: "Interface - %(asctime)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: xetra
      level: DEBUG
  root:
    level: DEBUG
    handlers: [ console ]